language: c
dist: focal
sudo: required

compiler:
  - gcc

before_install:
  - sudo apt-get install -y cmake
  - sudo apt-get install -y gcc
  - sudo apt-get install libglib2.0-dev

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test
  - ./test
